ARG IMAGE_TAG=latest
FROM centos:${IMAGE_TAG}
RUN rm -f /etc/system-release
RUN rm -f /etc/SuSE-release
RUN rm -f /etc/enterprise-release
RUN rm -f /etc/oracle-release
RUN rm -f /etc/fedora-release
RUN rm -f /etc/centos-release
RUN rm -f /etc/redhat-release
RUN rm -f /etc/alpine-release
RUN rm -f /etc/os-release
RUN rm -f /etc/debian_version
